apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m3ot0dczw-nodejs
  janus-idp.io/tekton: m3ot0dczw-nodejs
  backstage.io/kubernetes-id: m3ot0dczw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m3ot0dczw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
